### ISSUE TITLE
Rename Open Olat to OLAT

### ISSUE THREAD

**Issue by swissclash79** [SafeExamBrowser/seb-server#118]
Dear SEB Server team

Technically it is [OLAT](https://www.olat.org/) and not [OpenOlat](https://www.openolat.com/) that is supporting SEB Server.
So I changed it in the documentation and some code occurrences.

#117 

Best regards
Christian

**Comment by anhefti** [comment]
Dear Christian

Thanks for noticing this and doing a change request. And sorry that we confused this. I will apply your text changes as soon as possible also for the piplined patch release 1.6.1 as well as for the actual documentation.

Unfortunately the changes within the code regarding changing the name of an enumeration too, is not possible since there is legacy data in the database that depends on the enumeration names. But all text changes will be added.

Best regards
Andreas

**Comment by swissclash79** [comment]
Hello Andreas

Thank you very much for applying my changes!

Best regards
Christian

**Comment by anhefti** [comment]
Done
