### ISSUE TITLE
Building the development version

### ISSUE THREAD

**Issue by nimalr** [SafeExamBrowser/seb-server#23]
Hi,

I would like to build / test the development version which supposedly provides support for live proctoring.
Could not find any instructions on this in the documentation. Can you point me to a developers guide or
something similar?

Also, which branch should I start with - dev-1.1.0 or development?

Thank you.

Nimal R.

**Comment by anhefti** [comment]
Hi Nimal,

There is no documentation for the live proctoring feature for 1.1.0 yet, since the version 1.1.0 is not official released yet. 
If you want to try and test, you can use the dev-1.1.0 branch since this should be more stable. But please be aware that this is still in development and it is frequently updated at the moment. 

In the version 1.1.x the live proctoring is also still in a prototype state and runs only with a Jitsi Meet service that must be installed and running on its own. Please refer to the Jitsi Meet docker installation (https://github.com/jitsi/docker-jitsi-meet) to setup a Jitsi Meet service. 

In the Exam section of the SEB Server it is then possible to add the proctoring settings for an exam by giving the URL to the Jtisi Meet service and the app-credentials. Once the proctoring is enabled for a certain exam, it is applied within the monitoring view while the exam is running.
![exam_proctoring](https://user-images.githubusercontent.com/39078777/107919760-1be3d800-6f6c-11eb-979a-20e13d39e0ba.png)

**Comment by nimalr** [comment]
Resolved: 
Built the 1.1-latest by changing SEBSERVER_VERSION=1.1-latest in the docker-compose.yml
I will test with Jitsi service now.

**Comment by anhefti** [comment]
Please be aware that there is no official SEB Windows nor SEB Mac/iOS release that has proctoring integration with Jitsi Meet yet. 
There is a iOS early version SEB 2.1.5 that has the integration and is available through Testflight on iOS devices.  
SEB Windows client with proctoring integration with Jitsi Meet is planed for the next release 3.2.0

**Comment by nimalr** [comment]
Thanks. Yes - we are aware of the limitations.

**Comment by nimalr** [comment]
In Proctoring Settings we have to specify Application Key and secret. Could not find any documentation on these. I assume they are created on the Jitsi Meet server and entered here?

**Comment by anhefti** [comment]
Yes, Jitsi Meet server must enable [JWT authentication](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker). See chapter: "Authentication using JWT tokens"
