### ISSUE TITLE
Moodle Restrictions Plugin, release date

### ISSUE THREAD

**Issue by senapetschnig** [SafeExamBrowser/seb-server#25]
As far as i understand the actual integration or lets say combination of moodle and seb server, the feature of restricting quizes in the lms from sebserver is not working with moodle at the moment.
As the last version of the Moodle "Safe Exam Browser access rule" plugin, already has a lot of features also integrated which are implemented in the sebserver, i am curios in which direction these two separate products will go.
For a large institution the decision for one or the other will lead to some years of being stuck with it.

Even though i know it is hard to tell release dates for open source projects, it would be good to know for us, when a moodle restriction plugin which works with the sebserver could be released.
And also if this would be part of the actual SEB Moodle plugin or if it would be a seperate plugin?
If they are two plugins, could they coexist in moodle?

I would also like to thank you for the great products you are developing which are really a huge help in education, and especially helpful for educational institutions not getting bound to big companys and proprietary products.

**Comment by danschlet** [comment]
Thank you for your question. SEB Server support for all SEB client platforms and for Moodle are still in development, so it's not yet the time to make any public announcements about details and availability of a final version. We will communicate this at some point in the near future. 

Although there are some similarities about creating SEB configuration files, SEB Server is way more complex to set up, maintain and to use than the Safe Exam Browser access rule plugin (which is anyways included in Moodle). So we think it will be quite easy to decide which to use (after SEB Server support for Moodle is finalized): If you need live monitoring of exam clients and have the resources to set up and maintain an SEB Server, use that, otherwise use the standard SEB Moodle integration. The latter was developed externally together with the Moodle community and ETH Zurich just had the project lead. If there would be requests that the Moodle plugin integration should be extended, that discussion would need to be started in the Moodle community. I'm currently not aware of such a discussion.

The goal definitely is that the standard SEB Moodle integration and integration with SEB Server can coexist. Technical details are still being evaluated though.

There is a workaround to already use restricted Moodle quizzes together with SEB Server. Exam settings need to be configured in the Moodle 3.9+ access rule settings with this workaround, but at least you can set up which exams should be automatically presented to students in supported SEB clients and use the monitoring features in SEB Server during the exam.

- In SEB Server, use settings examSessionReconfigureAllow = true and the correct examSessionReconfigureConfigURL (sebs://examplemoodleserver.com/moodlepath/*) for the exam. Also set examSessionClearCookiesOnEnd = false.
- In the SEB quiz settings in Moodle upload a custom config file with the setting examSessionClearCookiesOnStart = false and all the other settings you require for the Moodle exam.

**Comment by fishfree** [comment]
@danschlet Please tell me where to configure examSessionReconfigureAllow and examSessionReconfigureConfigURL in SEB Server.

**Comment by anhefti** [comment]
Moodle Restrictions Plugin will be released with the next SEB Server release 1.5 in Q2 this year.

**Comment by lucaboesch** [comment]
That's today, ain't it 😉 ?

**Comment by anhefti** [comment]
Its out now, enjoy!
