### ISSUE TITLE
How to change the Date and Calendar format to other countries?

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-server#28]
Where to configure? and the supported locale list? please.
![image](https://user-images.githubusercontent.com/1741341/127286853-a9ce7c63-cf45-42ea-b8a3-477b2178a423.png)

**Comment by anhefti** [comment]
Hi, where to configure what exactly? Can you please give us a clear explanation of what you want to achieve!

The default timezone in SEB Server is UTC. If you want to define a timezone for a particular user, then you can do that within the user-account settings. SEB Server will then display the dates and times according to the time-zone of the user.

**Comment by fishfree** [comment]
@anhefti You said: _The date input field and picker popup cannot be changed since this comes from used framework._
I don't think so. Ususally popular picker popup calendar libraries considers internationalization. I also suggest just use the HTML 5 tag <input type="date"> instead, then browsers will render it appropriately.

**Comment by anhefti** [comment]
@fishfree Thanks for your suggestions. Since we use the Eclipse RAP framework for the SEB Server GUI, we cannot access HTML directly but all is generated by the framework and the framework is not very open. 

For next SEB Server version we have accessibility improvements in the pipeline and we will try to also tackle the date-picker within this issue but with no guarantee that it will work as expected (we still depend on the framework)
