### ISSUE TITLE
seb-server-setup logs error & nginx Bad Gateways (502 status code).

### ISSUE THREAD

**Issue by leuk7** [SafeExamBrowser/seb-server#38]
**Description:**
Hy. 
I am trying to setup the 'testing' envrionnement of SEB Server. But I think there is something wrong somewhere. 

- The first error is related to 'seb-server-setup' container where the logs says : '/bin/sh: sudo not found'
- The second one is about the proxy server. When I a try to access my server website (seb administration site), it says : '502: bad Gateway'
May be the my errors are related!

**To Reproduce**

- **Error 1**

1. Run the command 'docker-compose up -d', in '/sebserver/seb-server-setup/docker/testing/basic' folder
2. Watch  the 'seb-server-setup' logs files. In my case I use a Docker GUI App (DockStation)
3. See error

- **Error 2**
1. Run the command 'docker-compose up -d' in '/sebserver/seb-server-setup/docker/testing/basic' folder
2. Access the server with your browser
3. See error

**Screenshots**
- **Error 1**
![image](https://user-images.githubusercontent.com/68125778/134782749-2836df61-3020-4ccb-9acd-4c794416acb8.png)

- **Error 2**
![image](https://user-images.githubusercontent.com/68125778/134782797-add7aa21-a863-4ce5-87a5-728f97be94a7.png)

Another screenshoot of 'seb-server' container log
![image](https://user-images.githubusercontent.com/68125778/134788203-938ac643-3f39-489a-b50a-926d08824ddf.png)

**Setup :**
 - SEB Server Version [1.1.-latest]
 - Setup / IT environment the service is running on Ubuntu 20.04 LTS
 - Browser: Mozilla Firefox

**Comment by leuk7** [comment]
I found a solution to my problem: 

1. I needed to provide the server name as sugest in seb-server logs. The property is 'sebserver.webservice.http.external.servername' located in 'sebserver/seb-server-setup/docker/testing/basic/config/spring/application-prod.properties' 
2. Also I notice in 'setup.Dockerfile', there was a 'sudo' command which we do not really need. It was the one that caused the second error (/bin/sh: sudo nof found). I think we do not need it based on some discussions : https://stackoverflow.com/questions/56249601/bin-sh-1-sudo-not-found-when-running-dockerfile/56249679

Thanks guys!😉

**Comment by anhefti** [comment]
Hi, glad you've found a solution. 

The seb-sever-setup service is just used to put a password file for the other services into the internal docker volumes. If this is not working, the seb-server service will not startup correctly. As described within the installation guide, you only need to give this password once within the setup process and then you can start and stop your services without heaving to provide the file again until you delete ore prune the involved docker volumes. Please make also sure that you always give the same password if you have to setup SEB Server again with existing database data.

We added the "sudo" command in the setup.Dockerfile because in some setups it was needed to have access to the password file within the docker service. 

The configuration for the SEB Server service is located in the  '/config/spring/application-prod.properties' and here: https://seb-server-setup.readthedocs.io/en/latest/configuration.html you can find the descriptions for the different properties.
