### ISSUE TITLE
Make timezone also globally configuraable besides per user.

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-server#82]
Many thanks!

**Comment by anhefti** [comment]
The time zone can be set per User. The default Time zone globally is UTC.

**Comment by fishfree** [comment]
> The time zone can be set per User. The default Time zone globally is UTC.

I konw the time zone can be set per user, but cannot be set globally.

**Comment by anhefti** [comment]
No the global server time zone is always UTC, this is the reference time zone. All data is stored within this time zone. 
But when you use the application you always login with a user-account and this user account has a time-zone for the user. 
The reference time zone UTC will not be changed because this is bad practice and error prone and at the end it is an implementation detail and not a user dependent one.

The only thing we can think of is a new global SEB Server configuration setting like

sebserver.webservice.useraccount.default.timezone=utc

for example where one can set the initial timezone a user will have selected on registration or on creating a new user-account by an admin. This would only be configurable on SEB Server installation level. 

Is this what you would like to have?

**Comment by anhefti** [comment]
Internal Issue: SEBSERV-460

**Comment by anhefti** [comment]
Added new SEB Server setup property: 

sebserver.gui.registering.default.timeZone

Example:

sebserver.gui.registering.default.timeZone=Europe/Zurich

Available until SEB Server version 1.6
