### ISSUE TITLE
401 js error when view proctoring hall with Jitsi meet.

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-server#84]
The screenshot is as below:
![image](https://github.com/SafeExamBrowser/seb-server/assets/1741341/14321e82-c773-4f5c-9c61-d56952c9453b)
SEB server 1.5 stable, SEB: 3.5.0
#76

**Comment by anhefti** [comment]
It seems that you don't have access (401 = Access Denied) or the browser cannot cannot access the proctoring endpoint for some unknown reason. Could you please also give the respective SEB Server logs, eventually we can see some details there. Also the User and its roles would be of interest, that you used for proctoring access.

Please also note the Jitsi-Meet integration is still a prototype and has not been actively maintained since SEB Server version 1.3 anymore. The focus lies on Zoom integration but also in SEB but only with a special Alliance Version that is only available for [SEB Alliance](https://www.safeexambrowser.org/alliance/benefits.html) members.

**Comment by fishfree** [comment]
@anhefti Thank you very much! The 401 errored path was  under SEB Server domain, not under Jitsi meet. I'd configured JWT auth both sides.
Here is the log file:
[seb-docker.log](https://github.com/SafeExamBrowser/seb-server/files/11956007/seb-docker.log)

Hope for you help~

**Comment by anhefti** [comment]
Thanks, according to the log file there is a none ISO character that causes the problem when opening the proctoring window:

```
01:31:41.195 ERROR [http-nio-0.0.0.0-8080-exec-10]:[org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[proctoringServlet]] Servlet.service() for servlet [proctoringServlet] in context with path [] threw exception
java.io.CharConversionException: Not an ISO 8859-1 character: [市]
	at javax.servlet.ServletOutputStream.print(ServletOutputStream.java:78)
	at javax.servlet.ServletOutputStream.println(ServletOutputStream.java:192)
	at ch.ethz.seb.sebserver.gui.ProctoringServlet.doGet(ProctoringServlet.java:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
```

This may come from Jitsi user name or from the room name. Please make sure you only use ISO 8859-1 conform characters.
