### ISSUE TITLE
Why there is no session in a running exam?

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-server#87]
The screenshot of my SEB server is as below:
![image](https://github.com/SafeExamBrowser/seb-server/assets/1741341/204e3480-f353-48a1-9f1e-87ecd07a4298)

In fact, there is a Windows SEB client who is attending the exam when take the screenshot above. My SEB server is successfully connected with my Moodle server, and the exam is successfully imported from Moodle. I cannot figure out why.

**Comment by anhefti** [comment]
Hi, 

In this case (if you are in Moodle but not seeing anything in SEB Server) you probably use the wrong SEB configuration to start the SEB Client since the SEB client always should firstly connect to the SEB Server and if this is not possible gives an error message to the student. So either SEB was not able to connect to the SEB Server and you have set the link to the Moodle course as a fallback URL in the Connection Configuration for SEB Server or you don't use a Connection Configuration from SEB Server to start the SEB client. You can also consult the SEB Log files to check if SEB is connecting to SEB Server and if this fail, why it fails.

The easiest way to start your Exam with SEB and SEB Server is, to download the Connection Configuration from your Exam Setup. Then it will directly apply to the respective Exam. TO do so just download the Exam Connection Configuration here: 

![image](https://github.com/SafeExamBrowser/seb-server/assets/39078777/d9191fb4-3393-43ef-ac5c-095a58514941)


Please also read the User Manual since this process should also be described there: https://seb-server.readthedocs.io/en/latest/#

**Comment by fishfree** [comment]
@anhefti Thank you very much for your tip! Sorry for late response.
