### ISSUE TITLE
Can not show up examinees when proctoring with Jitsi Meet.

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-server#89]
I set up Jitsi meet proctoring as below:
![image](https://github.com/SafeExamBrowser/seb-server/assets/1741341/c35614bf-ef51-4b3f-adb9-43dbf1bbe478)
However, when I click on "View Room 1 (1/20)" on the "Running exams" page, it shows as below:
![image](https://github.com/SafeExamBrowser/seb-server/assets/1741341/ac6749e1-9d0d-4bfe-bdd0-c53ccbfdf494)

Only me, the proctor, no examinees, and the Safe Exam Browser 3.5.0 in the examinee's Windows does not invoke the webcam.

**Comment by anhefti** [comment]
Hi,

The "View Room 1 (1/20)" indicates that there should be one more participant in the room when the proctor connects. So it seems the SEB client was not able to connect to the Jitsi Meet meeting for some unknown reasons. I cannot se with the few information here why this is. We need at least the log-files of the SEB client and more information about SEB client version and eventually Jitsi Meets setup.

Please also be aware the Jitsi Meet for SEB and SEB Server is still in prototype phase and has not been improved since SEB Server 
version 1.2 where is was invented. The focus lies on Zoom integration for live proctoring with SEB and SEB Server.

**Comment by fishfree** [comment]
@anhefti Thank you! Which foldr the SEB log files locate?

**Comment by anhefti** [comment]
Hi, It seems that SEB was not able to get the Moodle session identifier from Moodle login and therefore was not able to finish up the SEB Server handshake. Only if the SEB Server handshake has successfully been finished, the SEB is instructed to connect to a meeting room.

Do you have some kind of AAI or LDAP or other SSO service to login into Moodle. If so, this can be caused by the SSO service preventing SEB to get the Moodle user identifer from Students Moodle login. In this case you either can try to use the new [Moodle SEB Server Plugin](https://seb-server.readthedocs.io/en/latest/lmssetup.html#install-seb-restriction-api-plugin) to connect SEB Server to Moodle. Or to find a workaround so that your SSO service provides the user id within the login response like Moodle do on the usual Moodle login.
