### ISSUE TITLE
Set SEB configuration passwords when importing an exam from Moodle

### ISSUE THREAD

**Issue by michaelhq** [SafeExamBrowser/seb-server#98]
Hello,

I have a feature request.

If you import an exam from Moodle, it would be very handy if you could set the passwords (admin and quit password) in the SEB settings right away. Or if you are using a template and there are already some passwords set in the settings template, adjust them. Because it is important to have at least a different quit password for different exams.

Currently, you have to open the SEB settings and change the passwords. If the exam configuration is already in the status "In Use", you first have to set it to "Under Construction" to adjust the passwords in the SEB settings. Then you have to set it to "In Use" again to make this configuration active. It would simplify this process if you could set an admin and quit password for the SEB configuration in the exam import dialog. Additionally, it would be handy if there was a function where you could view all set passwords for the exams as a list.

In connection with the Moodle SEB server quiz access plugin: It would also be great if you could see whether the Moodle quiz has set a password and if you could set a quiz password from the SEB server if necessary.

As a side note, even if you are using the "quit with link" option in SEB, it is important to set a quit password. E.g., a student can intentionally crash a computer during an exam, only a Quit password can ensure that the student cannot simply look up something on his computer before re-entering the SEB and the exam. Because with a quit password, the computer is locked after a reboot by the SEB. Only by entering a Quit password can the computer be unlocked,

Regards,
Michael

**Comment by michaelhq** [comment]
Hi Andreas,

Thank you for your prompt response and happy to hear that some requested functionality is on the roadmap of SEB server.

Yes, there are two requests for new functions.

The Moodle quiz password must be different from the quit password. In an exam situation, the Moodle quiz password is given at the beginning of the exam, and the SEB quit password is given at the end of the exam when all examinees have submitted the exam. If the quit password were given beforehand, then examinees could leave the SEB at will and re-enter the exam, which would allow cheating.

I emailed you directly to answer your last question.

Regards,
Michael

**Comment by anhefti** [comment]
Hi Michael

Unfortunately, we are not able to reproduce this issue even with imported SEB Settings configurations that were saved as Configuration Template. What we tried was the following:

Create a SEB Configuration with the SEB Config Tool (Windows) with URL filter:
![image](https://github.com/SafeExamBrowser/seb-server/assets/39078777/7ed22deb-17f8-444a-b666-7eff8d6b3dbf)

Import the SEB Configuration within SEB Server and save the imported Exam Configuration as Configuration Template:
![image](https://github.com/SafeExamBrowser/seb-server/assets/39078777/c9f07e7d-25f0-4895-8dcd-14f95cebe3a1)

Add new URL filter to the existing List:
![image](https://github.com/SafeExamBrowser/seb-server/assets/39078777/cd9efaac-4b0e-426b-9776-9e078bbd3d91)
![image](https://github.com/SafeExamBrowser/seb-server/assets/39078777/8e5aaa7a-f812-4ea6-b04c-5738f05431b9)

But we made this and other lists longer now within the Configuration Template so that the handling should be more convenient.

If the Issue still exists, it would be good to have an exact recipe of how to reproduce it with SEB Settings import.

Best Regards
Andreas
